# -*- coding: utf-8 -*-
"""重新生成 alembic/baseline_schema.sql（从当前数据库 SHOW CREATE TABLE 导出）。

用于 schema 整体基线需要重建时（新增了大量表）：
    python scripts/gen_schema.py

会连接 alembic.ini 里配置的数据库（默认 edu），导出全部表 DDL。
注意：alembic_version 表由 Alembic 管理，自动排除。
"""
from __future__ import annotations

import sys
from pathlib import Path

import pymysql

AGENT_ROOT = Path(__file__).resolve().parents[1]


def _load_url() -> dict:
    """从 alembic.ini 读 sqlalchemy.url，解析连接参数。"""
    import configparser

    cfg = configparser.ConfigParser()
    cfg.read(AGENT_ROOT / "alembic.ini", encoding="utf-8")
    url = cfg.get("alembic", "sqlalchemy.url")
    # mysql+pymysql://user:pass@host:port/db
    rest = url.split("://", 1)[1]
    cred, hostpart = rest.split("@", 1)
    user, pwd = cred.split(":", 1)
    if ":" in hostpart:
        host, portdb = hostpart.rsplit(":", 1)
        port, db = portdb.split("/", 1)
        port = int(port)
    else:
        host, db = hostpart.split("/", 1)
        port = 3306
    return {"host": host, "port": port, "user": user, "password": pwd, "database": db}


def main() -> int:
    params = _load_url()
    print(f"连接 {params['host']}:{params['port']}/{params['database']} ...")
    conn = pymysql.connect(
        host=params["host"], port=params["port"], user=params["user"],
        password=params["password"], database=params["database"], charset="utf8mb4",
    )
    cur = conn.cursor()
    cur.execute("SHOW TABLES")
    tables = [r[0] for r in cur.fetchall()]
    tables = [t for t in tables if t != "alembic_version"]
    print(f"共 {len(tables)} 张表")

    out = [
        "-- EduAgent baseline schema (generated by scripts/gen_schema.py)",
        f"-- {len(tables)} tables. Do not edit manually.",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS=0;",
    ]
    for t in tables:
        cur.execute(f"SHOW CREATE TABLE `{t}`")
        row = cur.fetchone()
        if row:
            out.append(f"-- table: {t}")
            out.append(row[1] + ";")
    out.append("SET FOREIGN_KEY_CHECKS=1;")

    dest = AGENT_ROOT / "alembic" / "baseline_schema.sql"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"已写入 {dest}")
    conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
